### ISSUE TITLE
Unable to obtain cluster list in bare-metal mode

### ISSUE THREAD

**Issue by sjcsjc123** [GreptimeTeam/gtctl#104]
I execute this command to start the cluster.
![image](https://github.com/GreptimeTeam/gtctl/assets/88550136/257cc4de-2e22-4e5c-b8cb-a8c459a92ef2)

Then i execute this command to get cluster list.
![image](https://github.com/GreptimeTeam/gtctl/assets/88550136/a18d34a6-7215-4869-ae85-0208500b1d84)

![image](https://github.com/GreptimeTeam/gtctl/assets/88550136/52170ee4-88ef-4dea-add3-049629752286)

**Comment by zyy17** [comment]
@sjcsjc123 It's not yet implemented(@shawnh2 is working on it). Maybe you can just use default values in #86 for a workaround.

**Comment by sjcsjc123** [comment]
I understand
