### ISSUE TITLE
Display more context on exit error

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/gtctl#110]
When process exit unexpected, gtctl will print an error like `binary '/path/to/greptimedb-dev/debug/greptime' exited with error: exit status 1`

But all three components are in this binary, I cannot figure out which component is wrong (especially when their log doesn't contains relative information). It would be better if we could also see some extra context, like the command of this binary, or the last 5 lines of logs, etc.

**Comment by shawnh2** [comment]
+1
