### ISSUE TITLE
The unified metadata management

### ISSUE THREAD

**Issue by zyy17** [GreptimeTeam/gtctl#150]
## Background

For different deployment modes, the gtctl needs to store the metadata in `.gtctl`, for example:

- The downloaded artifacts(I think we also need a unified artifacts manager https://github.com/GreptimeTeam/gtctl/issues/151);
- The deployment metadata (like dirs or files etc)

We should design a unified metadata management to handle the above scenarios, or similar logic will spread everywhere.

**Comment by shawnh2** [comment]
right now we have some basic implementation of these managers:
- artifacts manager #157 
- metadata manager #158 #169 

so close this one in favor of these PRs. will raise a new issue if we encounter some new cases.
