### ISSUE TITLE
Implement `gtctl cluster connect` subcommand

### ISSUE THREAD

**Issue by zyy17** [GreptimeTeam/gtctl#3]
Integrate multiple DB console(MySQL,pg,opentsdb...) in `gtctl`. When we execute the following command:

```
$ gtctl connect --type=mysql <your-greptimedb-service> <other-credentials>
mysql> SELECT * FROM monitor;

$ gtctl connect --type=pg <your-greptimedb-service> <other-credentials>
pg> SELECT * FROM monitor;
```

**Comment by wangeguo** [comment]
How about this: `gtctl connect mysql://user:password@host:port`

See more Data Source Name (DSN) information at https://en.wikipedia.org/wiki/Data_source_name

**Comment by zyy17** [comment]
@wangeguo yeap, I think your proposal is better! Using the DSN can be easy for users.

**Comment by sjcsjc123** [comment]
i want to try it

**Comment by sjcsjc123** [comment]
if the pr #86 is ok, i will add `gtctl connect pg` command

**Comment by zyy17** [comment]
@sjcsjc123 Sorry for my late response, I'll review it soon.

**Comment by zyy17** [comment]
@sjcsjc123 I think you can try `pg` 😊.

**Comment by sjcsjc123** [comment]
i will try it!

**Comment by shawnh2** [comment]
since we already implement the `connect` subcmd, and have support on `mysql` and `pg`. so close this one right now, if we need other support for this subcmd, feel free to raise a new issue.
