### ISSUE TITLE
The released arm64 binary doesn't work in ARM64 hardware architecture

### ISSUE THREAD

**Issue by yszjsnj** [GreptimeTeam/gtctl#48]

**Comment by yszjsnj** [comment]
-rwxr-xr-x  1 xinchuang docker  77964240 11月 10 19:10  gtctl
gtctl --help
-bash: /usr/local/bin/gtctl：无法执行二进制文件: 可执行文件格式错误

**Comment by zyy17** [comment]
@yszjsnj, thank you for your report! Can you provide more information about your environment? I think the output message of the following commands will be helpful:

```console
# print system information.
uname -a

# detect your binary type information.
file ./gtctl
```

**Comment by yszjsnj** [comment]
uname -a
Linux huawei-taishan-01 4.19.90-23.28.v2101.ky10.aarch64 #1 SMP Thu Sep 29 18:11:03 CST 2022 aarch64 aarch64 aarch64 GNU/Linux

file ./gtctl
./gtctl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=837832654baf3b66e385804bb27ca28fdaf3a58b, for GNU/Linux 3.2.0, not stripped

**Comment by yszjsnj** [comment]
文件是下载的gtctl-linux-arm64.tgz  为什么解压后不是arm的呢？

**Comment by yszjsnj** [comment]
cpu:  HUAWEI,Kunpeng 920

**Comment by yszjsnj** [comment]
file ./kind
./kind: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, not stripped

**Comment by zyy17** [comment]
Thank you for your information! It's a bug of the CI release process. The release action don't specify the `GOARCH=arm64` when compiling the `gtctl` binary. We will fix it soon.

**Comment by daviderli614** [comment]
Hi @yszjsnj , the fix solve in https://github.com/GreptimeTeam/gtctl/pull/49
