### ISSUE TITLE
Support complete configuration of gretimedb in bare metal mode

### ISSUE THREAD

**Issue by zyy17** [GreptimeTeam/gtctl#80]
## Background

The current implementation of bare metal deployment only supports a few configurations of multiple components. 

## Enhancement

1. Support to pass the toml configuration file;
2. For some very important arguments, we can extract them to the top level;

**Comment by sjcsjc123** [comment]
can it give more detail informance?

**Comment by zyy17** [comment]
@sjcsjc123 Hi! Sorry for my late response. I have already added some details to this issue.
