### ISSUE TITLE
bug:The installation process encountered an issue where the etcd package does not exist

### ISSUE THREAD

**Issue by sjcsjc123** [GreptimeTeam/gtctl#82]
When I execute the following command
`gtctl cluster create mycluster --bare-metal`
it happer error
![image](https://github.com/GreptimeTeam/gtctl/assets/88550136/debfb6c2-5a66-4fe9-a2ff-b20eff216c02)
then i find the zip file is no valid, i copy the download url and open the url, it return 404.
![image](https://github.com/GreptimeTeam/gtctl/assets/88550136/e9c28acd-d165-426d-ab37-7ed8a1a572f5)
Now, i found that there is no corresponding zip file in the download interface of [etcd]("https://github.com/etcd-io/etcd/releases")
![image](https://github.com/GreptimeTeam/gtctl/assets/88550136/0277b7dc-e4d3-4413-bfb7-4227250cb681)
It may be invalid to only determine whether the HTTP request was successful.
![image](https://github.com/GreptimeTeam/gtctl/assets/88550136/d9cb8509-deae-480a-976d-bf5360c65f2d)

**Comment by zyy17** [comment]
@sjcsjc123 Thank you for your bug report 😊! I think it's the bug. We should check whether the status code is 200 before the next process. For example(just for reference):

```go
...
if err != nil {
    return "", nil
}

if resp.StatusCode != http.StatusOK {
    resp.Body.Close()
    return "", fmt.Errorf("the http response code is '%d'", resp.StatusCode)
    
}
...
```

This bug may also exist elsewhere in the code. If you are interested, you can provide the PR to fix it 😊.

**Comment by sjcsjc123** [comment]
i will try it
