### ISSUE TITLE
Support golangci-lint to improve code quality

### ISSUE THREAD

**Issue by zyy17** [GreptimeTeam/gtctl#83]
The [golangci-lint](https://github.com/golangci/golangci-lint) is the great Go linter. We should:

1. Use golangci-lint and add the unified `.golangci.yml` file to make consistent behavior in CI and local testing;
2. Add the `lint` target in Makefile;
3. Use the same `.golangci.yml` in CI;

**Comment by sjcsjc123** [comment]
Is this to solve the workflow problem and what verification needs to be added?

**Comment by zyy17** [comment]
@sjcsjc123 Glad to see your interest! I have modified the issue description and hope it can help your understanding. Adding the `.golang.ci.yml` is the very important thing in Go ecosystem.

**Comment by sjcsjc123** [comment]
i can try this

**Comment by sjcsjc123** [comment]
![image](https://github.com/GreptimeTeam/gtctl/assets/88550136/97bcd6e5-235d-4463-ae45-c3ad0d9ece31)
The `ci` contains `golangci-lint`. Does it need to be extracted into a separate `ci` file. Another, I will add it in `Makefile`.

**Comment by zyy17** [comment]
@sjcsjc123 Are you still working on that? Sorry for missing the message, and I already created the related PR about the issue. If you are interested, you can review the PR.

**Comment by sjcsjc123** [comment]
No problem! I only added some content to the `Makefile`, which is not important.
