### ISSUE TITLE
Wrong etcd url for linux

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/gtctl#87]
https://github.com/etcd-io/etcd/releases/

Etcd has its linux binary packaged as tar.gz instead of zip so we always get an zip error after downloading etcd.

**Comment by zyy17** [comment]
@sunng87 maybe duplicated https://github.com/GreptimeTeam/gtctl/issues/82.

**Comment by sunng87** [comment]
Seems right. You might want to create a release for this bugfix.
