### ISSUE TITLE
Support all the arguments of greptime  helm chart for K8s deployment

### ISSUE THREAD

**Issue by zyy17** [GreptimeTeam/gtctl#91]
## Background

For the current implementation, gtctl can's support all the helm arguments in K8s deployment mode. 

## Enhancement

We can provide the following design:

1. Use like `helm --set <json>` to support all the arguments of the greptime helm chart;
2. For some key arguments, we can extract them to the top level;

The released issue https://github.com/GreptimeTeam/gtctl/issues/80 of bare metal.

**Comment by shawnh2** [comment]
consider solved on this one, if we need to surface more key arguments, we may arise other issue.
